modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Suiranoil/SkinRestorer/issues"
license = "MIT"

[[mods]]
modId = "skinrestorer"
version = "${version}"
displayName = "SkinRestorer"
authors = "Lionarius"
logoFile = "assets/skinrestorer/icon.png"
displayURL = "https://modrinth.com/mod/skinrestorer"
description = '''
A server-side mod for restoring skins on offline servers.
'''

[[dependencies.skinrestorer]]
modId = "neoforge"
mandatory = true
versionRange = "[20.3.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skinrestorer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3,1.20.4]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "skinrestorer-common.mixins.json"
